// PLANTILLA: rellenar el objeto fixes con las correcciones verificadas en el PDF y ejecutar: node fix.js test-oficial-conocimiento.html
const fs=require('fs');
const FILE=process.argv[2];
let s=fs.readFileSync(FILE,'utf8');
const BS=String.fromCharCode(92);
const L='ABCD';
const ex=(q,norma,cita,extra)=>`<span class="ex-resp">Respuesta correcta: <b>${L[q.correcta]}</b> · <mark class="ex-key">${q.opciones[q.correcta].replace(/\.$/,'')}</mark></span>${extra?extra+' ':''}Según el <span class="ref-norma">${norma}</span>: <span class="ref-concepto">"${cita}"</span> (verificado con el texto del temario).`;
const SBC='Reglamento (UE) 2016/399', F='Reglamento (UE) 2019/1896', P='Convenio de Prüm', D='Decisión 2008/615/JAI';
const fixes={
 '4-102':q=>{q.opciones[2]='El período determinado podrá prolongarse en tres ocasiones como máximo, por un nuevo período de hasta seis meses.';q.correcta=2;q.explicacion=ex(q,'art. 29.1 del '+SBC,'...por un período que no supere los seis meses. Ese período podrá prolongarse en tres ocasiones como máximo, por un nuevo período de hasta seis meses, en caso de que persistan las circunstancias excepcionales.','El texto vigente dice TRES ocasiones (no dos) y SEIS meses (no tres).')},
 '4-160':q=>{q.opciones[0]='Por un período que no supere los seis meses.';q.correcta=0;q.explicacion=ex(q,'art. 29.1 del '+SBC,'...los Estados miembros podrán restablecer los controles fronterizos en las fronteras interiores con arreglo al apartado 2 del presente artículo por un período que no supere los seis meses. Ese período podrá prolongarse en tres ocasiones como máximo...','Las opciones B y C son falsas porque dicen «dos ocasiones».')},
 '4-213':q=>{q.correcta=3;q.explicacion=ex(q,'art. 33.1 del '+SBC,'En el plazo de cuatro semanas desde la supresión de los controles fronterizos en las fronteras interiores, los Estados miembros que hayan realizado controles fronterizos en las fronteras interiores presentarán un informe al Parlamento Europeo, al Consejo y a la Comisión...')},
 '4-138':q=>{q.correcta=2;q.explicacion=ex(q,'art. 21.2 del '+SBC,'La Comisión informará periódicamente al Comité creado en virtud del artículo 38, apartado 1, sobre los avances en la aplicación de las medidas mencionadas en el apartado 1 del presente artículo y sobre su efecto en las deficiencias detectadas.')},
 '4-146':q=>{q.opciones[0]='Los menores de 12 años.';q.correcta=0;q.explicacion=ex(q,'art. 8 quater del '+SBC,'...se diseñarán, en la medida de lo posible, de forma que puedan ser utilizados por cualquier persona, excepto los menores de 12 años.')},
 '4-182':q=>{q.correcta=1;q.explicacion=ex(q,'art. 13.2 del '+F,'Los Estados miembros podrán designar a un máximo de dos miembros del personal que representen a su punto de contacto nacional en la Agencia como funcionarios de enlace.','No confundir con el funcionario de enlace DE LA AGENCIA (art. 31), que puede cubrir hasta cuatro Estados miembros.')},
 '4-97':q=>{q.correcta=0;q.explicacion=ex(q,'art. 39.5 del '+F,'El director ejecutivo tomará una decisión sobre la solicitud de iniciar una intervención fronteriza rápida en un plazo de dos días hábiles a partir de la fecha en la que se reciba dicha solicitud.','Secuencia: 2 días hábiles (decisión), 3 (plan operativo), 5 (primeros equipos) y 12 (equipos adicionales).')},
 '4-153':q=>{q.correcta=0;q.explicacion=ex(q,'art. 39.5 del '+F,'El director ejecutivo tomará una decisión sobre la solicitud de iniciar una intervención fronteriza rápida en un plazo de dos días hábiles a partir de la fecha en la que se reciba dicha solicitud.','Los cinco días hábiles son el plazo del despliegue de los primeros equipos (art. 39.14), no el de la decisión.')},
 '4-80':q=>{q.pregunta='Reglamento (UE) 2019/1896 (art. 91, Conservación de los datos). ¿Cuál es el período máximo durante el cual la Agencia podrá conservar los datos personales recogidos (art. 91.1)?';q.opciones[0]='Noventa días desde la fecha de recogida de dichos datos.';q.correcta=0;q.explicacion=ex(q,'art. 91.1 del '+F,'El período de conservación no superará en ningún caso los noventa días desde la fecha de recogida de dichos datos.','Los datos relativos al retorno se eliminan a más tardar treinta días después de terminar esas tareas (art. 91.2).')},
 '4-85':q=>{q.pregunta='Reglamento (UE) 2019/1896 (art. 84, Responsabilidad civil de los miembros del equipo). La responsabilidad civil por los daños causados por los miembros de los equipos en el Estado miembro de acogida: ¿qué afirmación es correcta?';q.opciones[2]='Recae en el Estado miembro de acogida; si el daño se debe a negligencia grave o dolo, este podrá pedir el reembolso al Estado miembro de origen (personal en comisión de servicios) o a la Agencia (personal estatutario).';q.correcta=2;q.explicacion=ex(q,'art. 84 del '+F,'Cuando tales daños y perjuicios sean consecuencia de negligencia grave o dolo de los miembros de los equipos enviados en comisión de servicios o desplegados por los Estados miembros, el Estado miembro de acogida podrá dirigirse al Estado miembro de origen para que le reembolse [...] Cuando [...] sean consecuencia de negligencia grave o dolo del personal estatutario de la Agencia, el Estado miembro de acogida podrá solicitar a la Agencia que le reembolse...')},
 '4-108':q=>{q.correcta=1;q.explicacion=ex(q,'art. 53 del '+F,'...el director ejecutivo tomará una decisión sobre el plan operativo [...] en un plazo máximo de cinco días hábiles.')},
 '4-163':q=>{q.opciones[2]='12 días hábiles.';q.correcta=2;q.explicacion=ex(q,'art. 39.14 del '+F,'Cuando resulte necesario, el despliegue de equipos de gestión de fronteras adicionales se llevará a cabo a más tardar en el plazo de doce días hábiles a partir de la fecha en que se haya acordado el plan operativo.','Ojo: son días HÁBILES (la opción A dice «naturales»).')},
 '4-199':q=>{q.correcta=0;q.explicacion=ex(q,'anexo V del '+F,'La formación continua anual debe durar un mínimo de veinticuatro horas en total, dedicando al menos ocho horas a la formación teórica y dieciséis a la práctica.')},
 '4-81':q=>{q.pregunta='Reglamento (UE) 2019/1896 (anexo I). ¿A partir de qué año alcanza el cuerpo permanente de la Guardia Europea de Fronteras y Costas (integrado por cuatro categorías de personal operativo) su capacidad de 10.000 efectivos?';q.correcta=0;q.explicacion=ex(q,'anexo I del '+F,'2027 y después: 3.000 / 1.500 / 5.500 / 0 = 10.000','El cuerpo permanente tiene CUATRO categorías (art. 54.1), no cinco.')},
 '4-59':q=>{q.correcta=1;q.explicacion=ex(q,'art. 37.3 del '+P,'En lugar de la supresión se procederá al bloqueo de los datos, con arreglo al derecho interno, cuando existan motivos para creer que la supresión podría afectar a intereses dignos de protección de la persona concernida.')},
 '4-164':q=>{q.correcta=2;q.explicacion=ex(q,'art. 33 de la '+D,'El Consejo, por mayoría cualificada y previa consulta al Parlamento Europeo, adoptará las medidas necesarias para la ejecución de la presente Decisión a escala de la Unión.','La unanimidad corresponde al Comité de Ministros del CONVENIO de Prüm (art. 43), no a la Decisión.')},
 '4-201':q=>{q.correcta=1;q.explicacion=ex(q,'art. 35.4 de la '+D,'En un plazo de cuatro semanas a partir de la fecha en que la presente Decisión surta efecto, los Estados miembros informarán al Consejo y a la Comisión de los acuerdos o convenios existentes...','Los NUEVOS acuerdos se comunican en tres meses desde su firma (art. 35.5).')},
 '4-224':q=>{q.correcta=3;q.explicacion=ex(q,'art. 39.1 del '+P+' (y art. 30 de la '+D+')','La documentación comprenderá los extremos siguientes: el motivo de la transmisión, los datos transmitidos, la fecha de la transmisión y la designación o identificación de la instancia que realice la consulta y la titular del fichero.','«La persona responsable del tratamiento» no figura en la lista; el motivo de la transmisión sí.')},
 '4-1':q=>{q.opciones[3]='Los agentes destacados por otros Estados miembros para que participen en operaciones conjuntas se atendrán a las instrucciones impartidas por la autoridad competente del Estado miembro de acogida.';q.correcta=3;q.explicacion=ex(q,'art. 17.3 de la '+D,'Los agentes destacados por otros Estados miembros para que participen en operaciones conjuntas se atendrán a las instrucciones impartidas por la autoridad competente del Estado miembro de acogida.')},
};
let n=0;
for(const id in fixes){
  const key='{"id":"'+id+'"';
  const i=s.indexOf(key);if(i<0){console.log('NOT FOUND',id);continue}
  if(s.indexOf(key,i+1)>=0)console.log('WARN dup',id);
  let d=0,inS=false,esc=false,j=i;
  for(;j<s.length;j++){const c=s[j];
    if(inS){if(esc)esc=false;else if(c===BS)esc=true;else if(c==='"')inS=false;continue}
    if(c==='"')inS=true;else if(c==='{')d++;else if(c==='}'){d--;if(d===0)break}}
  const q=JSON.parse(s.slice(i,j+1));
  fixes[id](q);
  s=s.slice(0,i)+JSON.stringify(q)+s.slice(j+1);n++;
}
fs.writeFileSync(FILE,s);console.log('fixed',n);
