// Preguntas OFICIALES nuevas (redactadas como de examen) para los artículos marcados por el usuario con EX / EXOF / EXAMEN 2020
// en su temario del Tema 11 que no tenían ninguna pregunta oficial en el banco. Texto literal del extracto oficial.
// Uso: node prompts/herramientas/preguntas-ex-t11.js   (idempotente: salta los ids que ya existen; inserta tras 11-173)
const fs = require('fs');
const F = 'test-oficial-conocimiento.html';
const N = {
  l39: ['Ley 39/2015', 'Ley 39/2015, de 1 de octubre, del Procedimiento Administrativo Común de las Administraciones Públicas'],
  l40: ['Ley 40/2015', 'Ley 40/2015, de 1 de octubre, de Régimen Jurídico del Sector Público'],
  l19: ['Ley 19/2013', 'Ley 19/2013, de 9 de diciembre, de transparencia, acceso a la información pública y buen gobierno'],
  rd: ['RD 179/2005', 'Real Decreto 179/2005, sobre prevención de riesgos laborales en la Guardia Civil'],
  lo3: ['LO 3/2018', 'Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales'] };
const NOMBRE = { l39: 'Ley 39/2015, de 1 de octubre, del Procedimiento Administrativo Común de las Administraciones Públicas', l40: 'Ley 40/2015, de 1 de octubre, de Régimen Jurídico del Sector Público', l19: 'Ley 19/2013, de 9 de diciembre, de Transparencia, Acceso a la Información Pública y Buen Gobierno', rd: 'Real Decreto 179/2005, de 18 de febrero, sobre prevención de riesgos laborales en la Guardia Civil', lo3: 'Ley Orgánica 3/2018, de Protección de Datos Personales y garantía de los derechos digitales' };
// [norma, art, materia, enunciado, correcta, [3 distractores], cita literal, (neg: texto de por qué es incorrecta)]
const Q = [
['l39', '66', 'Solicitudes de iniciación', 'Respecto del contenido de las solicitudes de iniciación, señale la opción correcta:', 'Deberán contener la identificación del medio electrónico o, en su defecto, el lugar físico en que desea que se practique la notificación.', ['Deberán contener, en todo caso, la dirección de correo electrónico del interesado.', 'La firma del solicitante no podrá sustituirse por la acreditación de la autenticidad de su voluntad por otro medio.', 'Las oficinas de asistencia en materia de registros no están obligadas a facilitar el código de identificación del órgano si el interesado lo desconoce.'], 'Identificación del medio electrónico, o en su defecto, lugar físico en que desea que se practique la notificación.'],
['l39', '76', 'Alegaciones', 'Los interesados podrán, en cualquier momento del procedimiento, aducir alegaciones y aportar documentos u otros elementos de juicio, siempre que sea anterior a:', 'El trámite de audiencia.', ['El acuerdo de iniciación.', 'El período de prueba.', 'La emisión de los informes preceptivos.'], 'Los interesados podrán, en cualquier momento del procedimiento anterior al trámite de audiencia, aducir alegaciones y aportar documentos u otros elementos de juicio.'],
['l39', '101', 'Apremio sobre el patrimonio', 'En cualquier caso, no podrá imponerse a los administrados una obligación pecuniaria que no estuviese establecida con arreglo a:', 'Una norma de rango legal.', ['Una norma de rango reglamentario.', 'Un acto administrativo firme.', 'La resolución del órgano competente en materia de recaudación.'], 'En cualquier caso no podrá imponerse a los administrados una obligación pecuniaria que no estuviese establecida con arreglo a una norma de rango legal.'],
['l39', '102', 'Ejecución subsidiaria', 'En relación con la ejecución subsidiaria, señale la INCORRECTA:', 'El importe de los gastos, daños y perjuicios no podrá liquidarse de forma provisional ni exigirse antes de la ejecución.', ['Habrá lugar a ella cuando se trate de actos que, por no ser personalísimos, puedan ser realizados por sujeto distinto del obligado.', 'Las Administraciones Públicas realizarán el acto, por sí o a través de las personas que determinen, a costa del obligado.', 'El importe de los gastos, daños y perjuicios se exigirá conforme a lo dispuesto para el apremio sobre el patrimonio.'], 'Dicho importe podrá liquidarse de forma provisional y realizarse antes de la ejecución, a reserva de la liquidación definitiva.', 'el artículo 102.4 permite liquidar el importe de forma provisional y realizarlo antes de la ejecución, a reserva de la liquidación definitiva.'],
['l39', '103', 'Multa coercitiva', 'Respecto de la multa coercitiva, señale la opción correcta:', 'Es independiente de las sanciones que puedan imponerse con tal carácter y compatible con ellas.', ['Es incompatible con las sanciones que puedan imponerse con tal carácter.', 'Puede imponerse aunque ninguna Ley la autorice, si el órgano lo estima conveniente.', 'Solo puede imponerse una vez, sin que pueda reiterarse por lapsos de tiempo.'], 'La multa coercitiva es independiente de las sanciones que puedan imponerse con tal carácter y compatible con ellas.'],
['l39', '104', 'Compulsión sobre las personas', 'Los actos administrativos que impongan una obligación personalísima de no hacer o soportar podrán ser ejecutados por compulsión directa sobre las personas:', 'En los casos en que la ley expresamente lo autorice, y dentro siempre del respeto debido a su dignidad y a los derechos reconocidos en la Constitución.', ['En todo caso, sin necesidad de habilitación legal expresa.', 'Solo mediante autorización judicial previa, aunque la ley lo autorice.', 'Cuando lo acuerde de forma motivada el órgano competente, aunque la ley no lo prevea.'], 'Podrán ser ejecutados por compulsión directa sobre las personas en los casos en que la ley expresamente lo autorice, y dentro siempre del respeto debido a su dignidad y a los derechos reconocidos en la Constitución.'],
['l39', '109', 'Revocación de actos', 'Las Administraciones Públicas podrán revocar sus actos de gravamen o desfavorables mientras no haya transcurrido:', 'El plazo de prescripción.', ['El plazo de un año desde su notificación.', 'El plazo de seis meses desde su firmeza.', 'El plazo de interposición del recurso de alzada.'], 'Las Administraciones Públicas podrán revocar, mientras no haya transcurrido el plazo de prescripción, sus actos de gravamen o desfavorables.'],
['l39', '110', 'Límites de la revisión', 'Las facultades de revisión no podrán ser ejercidas cuando su ejercicio resulte contrario a:', 'La equidad, a la buena fe, al derecho de los particulares o a las leyes.', ['La equidad, a la buena fe y al interés público.', 'La seguridad jurídica, a la igualdad y a las leyes.', 'La equidad, a la buena fe y al principio de proporcionalidad.'], 'Su ejercicio resulte contrario a la equidad, a la buena fe, al derecho de los particulares o a las leyes.'],
['l39', '111', 'Competencia para la revisión de oficio', 'En el ámbito estatal, es competente para la revisión de oficio de los actos y disposiciones dictados por los Ministros:', 'El Consejo de Ministros.', ['El Presidente del Gobierno.', 'El Secretario de Estado respectivo.', 'El Subsecretario del Departamento.'], 'El Consejo de Ministros, respecto de sus propios actos y disposiciones y de los actos y disposiciones dictados por los Ministros.'],
['l39', '114', 'Fin de la vía administrativa', 'En relación con los actos que ponen fin a la vía administrativa, señale la INCORRECTA:', 'Las resoluciones de los órganos administrativos que carezcan de superior jerárquico, en todo caso, sin que una Ley pueda establecer lo contrario.', ['Las resoluciones de los recursos de alzada.', 'La resolución administrativa de los procedimientos de responsabilidad patrimonial, cualquiera que fuese el tipo de relación, pública o privada, de que derive.', 'Los acuerdos, pactos, convenios o contratos que tengan la consideración de finalizadores del procedimiento.'], 'Las resoluciones de los órganos administrativos que carezcan de superior jerárquico, salvo que una Ley establezca lo contrario.', 'el artículo 114.1.c) pone fin a la vía administrativa a las resoluciones de los órganos que carezcan de superior jerárquico «salvo que una Ley establezca lo contrario».'],
['l39', '115', 'Interposición de recurso', 'El error o la ausencia de la calificación del recurso por parte del recurrente:', 'No será obstáculo para su tramitación, siempre que se deduzca su verdadero carácter.', ['Determinará la inadmisión del recurso.', 'Obligará a requerir su subsanación, archivándose si no se atiende.', 'Solo será subsanable si el recurso lo firma un letrado.'], 'El error o la ausencia de la calificación del recurso por parte del recurrente no será obstáculo para su tramitación, siempre que se deduzca su verdadero carácter.'],
['l39', '118', 'Audiencia en los recursos', 'Cuando en la resolución de un recurso hayan de tenerse en cuenta nuevos hechos o documentos no recogidos en el expediente originario, se pondrán de manifiesto a los interesados para que, en un plazo no inferior a diez días ni superior a quince:', 'Formulen las alegaciones y presenten los documentos y justificantes que estimen procedentes.', ['Subsanen el recurso y aporten el justificante del pago de la tasa.', 'Soliciten la práctica de nuevas pruebas ante el órgano instructor.', 'Desistan del recurso o se ratifiquen en sus pretensiones.'], 'Se pondrán de manifiesto a los interesados para que, en un plazo no inferior a diez días ni superior a quince, formulen las alegaciones y presenten los documentos y justificantes que estimen procedentes.'],
['l39', '119', 'Resolución del recurso', 'La resolución del recurso será congruente con las peticiones formuladas por el recurrente, sin que en ningún caso pueda:', 'Agravarse su situación inicial.', ['Estimarse en parte.', 'Ordenarse la retroacción del procedimiento.', 'Declararse su inadmisión.'], 'La resolución será congruente con las peticiones formuladas por el recurrente, sin que en ningún caso pueda agravarse su situación inicial.'],
['l39', '121', 'Objeto del recurso de alzada', 'Si el recurso de alzada se hubiera interpuesto ante el órgano que dictó el acto impugnado, éste deberá remitirlo al competente para resolverlo, con su informe y con una copia completa y ordenada del expediente, en el plazo de:', 'Diez días.', ['Cinco días.', 'Quince días.', 'Un mes.'], 'Éste deberá remitirlo al competente en el plazo de diez días, con su informe y con una copia completa y ordenada del expediente.'],
['l39', '123', 'Recurso potestativo de reposición', 'Los actos administrativos que pongan fin a la vía administrativa podrán ser recurridos potestativamente en reposición ante:', 'El mismo órgano que los hubiera dictado.', ['El órgano superior jerárquico del que los dictó.', 'El Ministro del Departamento correspondiente.', 'El órgano competente por razón de la materia en el ámbito de la Administración General del Estado.'], 'Podrán ser recurridos potestativamente en reposición ante el mismo órgano que los hubiera dictado o ser impugnados directamente ante el orden jurisdiccional contencioso-administrativo.'],
['l39', '126', 'Resolución del recurso extraordinario de revisión', 'Transcurrido el plazo de tres meses desde la interposición del recurso extraordinario de revisión sin haberse dictado y notificado la resolución, se entenderá:', 'Desestimado, quedando expedita la vía jurisdiccional contencioso-administrativa.', ['Estimado por silencio administrativo.', 'Inadmitido, debiendo el interesado reiterar su solicitud.', 'Pendiente de resolución, sin que quede expedita la vía jurisdiccional.'], 'Transcurrido el plazo de tres meses desde la interposición del recurso extraordinario de revisión sin haberse dictado y notificado la resolución, se entenderá desestimado, quedando expedita la vía jurisdiccional contencioso-administrativa.'],
['l39', '127', 'Iniciativa legislativa', 'El Gobierno de la Nación ejercerá la iniciativa legislativa prevista en la Constitución mediante la elaboración y aprobación de:', 'Los anteproyectos de Ley y la ulterior remisión de los proyectos de ley a las Cortes Generales.', ['Las proposiciones de ley y su ulterior remisión al Consejo de Estado.', 'Los reales decretos legislativos y su ulterior remisión al Congreso.', 'Los proyectos de reglamento y su ulterior remisión a las Cortes Generales.'], 'El Gobierno de la Nación ejercerá la iniciativa legislativa prevista en la Constitución mediante la elaboración y aprobación de los anteproyectos de Ley y la ulterior remisión de los proyectos de ley a las Cortes Generales.'],
['l39', '131', 'Publicidad de las normas', 'La publicación del «Boletín Oficial del Estado» en la sede electrónica del Organismo competente tendrá carácter:', 'Oficial y auténtico en las condiciones y con las garantías que se determinen reglamentariamente.', ['Meramente informativo, prevaleciendo siempre la edición impresa.', 'Oficial solo si se acompaña de edición impresa.', 'Oficial y auténtico sin necesidad de condiciones ni garantías adicionales.'], 'La publicación del «Boletín Oficial del Estado» en la sede electrónica del Organismo competente tendrá carácter oficial y auténtico en las condiciones y con las garantías que se determinen reglamentariamente.'],
['l39', '21', 'Obligación de resolver', 'El plazo máximo en el que debe notificarse la resolución expresa será el fijado por la norma reguladora del procedimiento. Este plazo no podrá exceder de:', 'Seis meses, salvo que una norma con rango de ley establezca uno mayor o así venga previsto en el Derecho de la Unión Europea.', ['Tres meses, salvo que una norma con rango de ley establezca uno mayor.', 'Un año, salvo que el Consejo de Ministros acuerde su ampliación.', 'Seis meses, sin posibilidad de que una norma establezca uno mayor.'], 'Este plazo no podrá exceder de seis meses, salvo que una norma con rango de ley establezca uno mayor o así venga previsto en el Derecho de la Unión Europea.'],
['l39', '56', 'Medidas provisionales', 'Las medidas provisionales adoptadas antes de la iniciación del procedimiento deberán ser confirmadas, modificadas o levantadas en el acuerdo de iniciación, que deberá efectuarse dentro de:', 'Los quince días siguientes a su adopción.', ['Los diez días siguientes a su adopción.', 'Los cinco días siguientes a su adopción.', 'El mes siguiente a su adopción.'], 'Las medidas provisionales deberán ser confirmadas, modificadas o levantadas en el acuerdo de iniciación del procedimiento, que deberá efectuarse dentro de los quince días siguientes a su adopción.'],
['l40', '34', 'Indemnización', 'Sólo serán indemnizables las lesiones producidas al particular provenientes de daños que éste:', 'No tenga el deber jurídico de soportar de acuerdo con la Ley.', ['Haya podido prever o evitar según el estado de los conocimientos de la ciencia o de la técnica.', 'No hubiera causado con culpa o negligencia propia.', 'Hubiera reclamado en el plazo de un mes desde que se produjeron.'], 'Sólo serán indemnizables las lesiones producidas al particular provenientes de daños que éste no tenga el deber jurídico de soportar de acuerdo con la Ley.'],
['l40', '38', 'La sede electrónica', 'El establecimiento de una sede electrónica conlleva la responsabilidad del titular respecto de:', 'La integridad, veracidad y actualización de la información y los servicios a los que pueda accederse a través de la misma.', ['La disponibilidad del servicio, excluida la veracidad de la información publicada.', 'La identificación de los ciudadanos que accedan a ella, exclusivamente.', 'La custodia de los documentos archivados en ella, sin responsabilidad sobre su actualización.'], 'El establecimiento de una sede electrónica conlleva la responsabilidad del titular respecto de la integridad, veracidad y actualización de la información y los servicios a los que pueda accederse a través de la misma.'],
['l40', '42', 'Sistemas de firma en la actuación automatizada', 'En la actuación administrativa automatizada, cada Administración Pública podrá determinar los supuestos de utilización de los siguientes sistemas de firma electrónica:', 'Sello electrónico de Administración Pública, órgano, organismo público o entidad de derecho público, y código seguro de verificación vinculado a la Administración Pública, órgano, organismo público o entidad de Derecho Público.', ['Firma electrónica avanzada del titular del órgano y certificado de empleado público.', 'Documento nacional de identidad electrónico y sistema de clave concertada.', 'Sello de tiempo y firma manuscrita digitalizada del titular del órgano.'], 'Sello electrónico de Administración Pública, órgano, organismo público o entidad de derecho público, [...] y código seguro de verificación vinculado a la Administración Pública, órgano, organismo público o entidad de Derecho Público.'],
['l40', '46', 'Archivo electrónico de documentos', 'Todos los documentos utilizados en las actuaciones administrativas se almacenarán por medios electrónicos:', 'Salvo cuando no sea posible.', ['Salvo cuando el interesado se oponga expresamente.', 'Salvo los que afecten a derechos o intereses de los particulares.', 'Salvo los generados por órganos colegiados.'], 'Todos los documentos utilizados en las actuaciones administrativas se almacenarán por medios electrónicos, salvo cuando no sea posible.'],
['l40', '50', 'Trámites preceptivos para la suscripción de convenios', 'Los convenios que suscriba la Administración General del Estado deberán acompañarse del informe de su servicio jurídico, que deberá emitirse en un plazo máximo de:', 'Siete días hábiles desde su solicitud.', ['Tres días hábiles desde su solicitud.', 'Diez días hábiles desde su solicitud.', 'Quince días naturales desde su solicitud.'], 'El informe de su servicio jurídico, que deberá emitirse en un plazo máximo de siete días hábiles desde su solicitud, transcurridos los cuales se continuará la tramitación.'],
['l40', '58', 'Organización interna de los Ministerios', 'Los Ministerios contarán, en todo caso, con:', 'Una Subsecretaría, y dependiendo de ella una Secretaría General Técnica, para la gestión de los servicios comunes.', ['Una Secretaría de Estado, y dependiendo de ella una Secretaría General.', 'Una Secretaría General Técnica, y dependiendo de ella una Subsecretaría.', 'Una Dirección General, y dependiendo de ella una Subdirección General.'], 'Los Ministerios contarán, en todo caso, con una Subsecretaría, y dependiendo de ella una Secretaría General Técnica, para la gestión de los servicios comunes previstos en este Título.'],
['l40', '59', 'Creación de órganos y unidades administrativas', 'Las Subsecretarías, las Secretarías Generales, las Secretarías Generales Técnicas, las Direcciones Generales y las Subdirecciones Generales se crean, modifican y suprimen por:', 'Real Decreto del Consejo de Ministros, a iniciativa del Ministro interesado y a propuesta del Ministro de Hacienda y Administraciones Públicas.', ['Orden del Ministro respectivo, previa autorización del Ministro de Hacienda y Administraciones Públicas.', 'Real Decreto del Presidente del Gobierno, a propuesta del Ministro interesado.', 'Orden del Ministro de Hacienda y Administraciones Públicas, a iniciativa del Ministro interesado.'], 'Se crean, modifican y suprimen por Real Decreto del Consejo de Ministros, a iniciativa del Ministro interesado y a propuesta del Ministro de Hacienda y Administraciones Públicas.'],
['l40', '60', 'Ordenación jerárquica de los órganos ministeriales', 'En la ordenación jerárquica de los órganos ministeriales, los Secretarios generales tienen categoría de ______ y los Secretarios Generales Técnicos tienen categoría de ______, respectivamente:', 'Subsecretario y Director general.', ['Director general y Subdirector general.', 'Secretario de Estado y Subsecretario.', 'Subsecretario y Subdirector general.'], 'Los Secretarios generales tienen categoría de Subsecretario y los Secretarios Generales Técnicos tienen categoría de Director general.'],
['l40', '63', 'Los Subsecretarios', 'Los Subsecretarios ostentan la representación ordinaria:', 'Del Ministerio.', ['Del Gobierno en el territorio de la Comunidad Autónoma.', 'De la Secretaría de Estado correspondiente.', 'De la Administración General del Estado ante las Cortes Generales.'], 'Los Subsecretarios ostentan la representación ordinaria del Ministerio, dirigen los servicios comunes, ejercen las competencias correspondientes a dichos servicios comunes y, en todo caso, las siguientes.'],
['l40', '65', 'Los Secretarios generales técnicos', 'Los Secretarios generales técnicos serán nombrados y separados por:', 'Real Decreto del Consejo de Ministros a propuesta del titular del Ministerio.', ['Orden del Ministro del Departamento.', 'Real Decreto del Presidente del Gobierno, a propuesta del Subsecretario.', 'Acuerdo del Subsecretario, previa autorización del Ministro de Hacienda.'], 'Los Secretarios generales técnicos serán nombrados y separados por Real Decreto del Consejo de Ministros a propuesta del titular del Ministerio.'],
['l40', '66', 'Los Directores generales', 'Los Directores generales son los titulares de los órganos directivos encargados de:', 'La gestión de una o varias áreas funcionalmente homogéneas del Ministerio.', ['La gestión de un sector de actividad administrativa.', 'La prestación de los servicios comunes del Departamento.', 'La dirección de los servicios territoriales del Ministerio.'], 'Los Directores generales son los titulares de los órganos directivos encargados de la gestión de una o varias áreas funcionalmente homogéneas del Ministerio.'],
['l40', '70', 'Los Directores Insulares', 'Los Directores Insulares de la Administración General del Estado serán nombrados:', 'Por el Delegado del Gobierno, mediante el procedimiento de libre designación entre funcionarios de carrera pertenecientes a Cuerpos o Escalas clasificados como Subgrupo A1.', ['Por el Subdelegado del Gobierno, mediante concurso entre funcionarios del Subgrupo A2.', 'Por el Consejo de Ministros, a propuesta del Ministro de Hacienda y Administraciones Públicas.', 'Por el Ministro de Hacienda y Administraciones Públicas, mediante libre designación entre cualquier empleado público.'], 'Serán nombrados por el Delegado del Gobierno mediante el procedimiento de libre designación entre funcionarios de carrera del Estado, de las Comunidades Autónomas o de las Entidades Locales, pertenecientes a Cuerpos o Escalas clasificados como Subgrupo A1.'],
['l40', '73', 'Competencias de los Delegados del Gobierno', 'Corresponde a los Delegados del Gobierno en las Comunidades Autónomas:', 'Nombrar a los Subdelegados del Gobierno en las provincias de su ámbito de actuación y, en su caso, a los Directores Insulares.', ['Designar a los Subsecretarios de los Ministerios con sede en la Comunidad.', 'Aprobar los reales decretos de estructura de las Delegaciones del Gobierno.', 'Presidir la Conferencia Sectorial correspondiente.'], 'Nombrar a los Subdelegados del Gobierno en las provincias de su ámbito de actuación y, en su caso, a los Directores Insulares.'],
['l40', '75', 'Competencias de los Subdelegados del Gobierno', 'A los Subdelegados del Gobierno en las provincias les corresponde, entre otras funciones:', 'Mantener las necesarias relaciones de cooperación y coordinación de la Administración General del Estado y sus Organismos públicos con la de la Comunidad Autónoma y con las correspondientes Entidades locales en el ámbito de la provincia.', ['Presidir la Comisión territorial de asistencia al Delegado del Gobierno.', 'Nombrar a los Delegados del Gobierno en las Comunidades Autónomas.', 'Ejercer la iniciativa legislativa de la Comunidad Autónoma.'], 'Mantener las necesarias relaciones de cooperación y coordinación de la Administración General del Estado y sus Organismos públicos con la de la Comunidad Autónoma y con las correspondientes Entidades locales en el ámbito de la provincia.'],
['l40', '78', 'Comisión interministerial de coordinación de la Administración periférica', 'La Comisión interministerial de coordinación de la Administración periférica del Estado es un órgano colegiado adscrito al:', 'Ministerio de Hacienda y Administraciones Públicas.', ['Ministerio del Interior.', 'Ministerio de la Presidencia.', 'Ministerio de Política Territorial.'], 'La Comisión interministerial de coordinación de la Administración periférica del Estado es un órgano colegiado, adscrito al Ministerio de Hacienda y Administraciones Públicas.'],
['l40', '79', 'Órganos colegiados de asistencia al Delegado y al Subdelegado', 'En cada una de las Comunidades Autónomas pluriprovinciales existirá una Comisión territorial de asistencia al Delegado del Gobierno, que:', 'Estará presidida por el Delegado del Gobierno en la Comunidad Autónoma e integrada por los Subdelegados del Gobierno en las provincias comprendidas en el territorio de ésta.', ['Estará presidida por el Presidente de la Comunidad Autónoma e integrada por los Directores Insulares.', 'Estará presidida por el Subdelegado del Gobierno de la provincia con mayor población e integrada por los Delegados de cada Ministerio.', 'Estará presidida por el Ministro de Hacienda y Administraciones Públicas e integrada por los Delegados del Gobierno.'], 'Estará presidida por el Delegado del Gobierno en la Comunidad Autónoma e integrada por los Subdelegados del Gobierno en las provincias comprendidas en el territorio de ésta.'],
['l40', '144', 'Técnicas de cooperación', 'Se podrá dar cumplimiento al principio de cooperación de acuerdo con las técnicas que las Administraciones interesadas estimen más adecuadas, como pueden ser:', 'La participación en órganos de cooperación, con el fin de deliberar y, en su caso, acordar medidas en materias sobre las que tengan competencias diferentes Administraciones Públicas.', ['La avocación de competencias de otra Administración mediante acuerdo del Consejo de Ministros.', 'La sustitución de la actividad de otra Administración sin necesidad de su conformidad.', 'La imposición de planes de cooperación por la Administración General del Estado.'], 'La participación en órganos de cooperación, con el fin de deliberar y, en su caso, acordar medidas en materias sobre las que tengan competencias diferentes Administraciones Públicas.'],
['l40', '145', 'Órganos de cooperación', 'Los órganos de cooperación entre distintas Administraciones Públicas en los que participe la Administración General del Estado deberán inscribirse, para que resulte válida su sesión constitutiva, en:', 'El Registro estatal de Órganos e Instrumentos de Cooperación.', ['El Registro Mercantil Central.', 'El Registro de Entidades del Sector Público Estatal.', 'El Boletín Oficial del Estado, mediante publicación íntegra de su norma de creación.'], 'Deberán inscribirse en el Registro estatal de Órganos e Instrumentos de Cooperación para que resulte válida su sesión constitutiva.'],
['l40', '146', 'Conferencia de Presidentes', 'La Conferencia de Presidentes es un órgano de cooperación multilateral entre el Gobierno de la Nación y los respectivos Gobiernos de las Comunidades Autónomas que está formada por:', 'El Presidente del Gobierno, que la preside, y por los Presidentes de las Comunidades Autónomas y de las Ciudades de Ceuta y Melilla.', ['El Ministro de Política Territorial, que la preside, y los Consejeros de cada Comunidad Autónoma.', 'El Presidente del Gobierno y los Delegados del Gobierno en las Comunidades Autónomas.', 'Los Presidentes de las Comunidades Autónomas, que eligen entre ellos a quien la preside.'], 'Está formada por el Presidente del Gobierno, que la preside, y por los Presidentes de las Comunidades Autónomas y de las Ciudades de Ceuta y Melilla.'],
['l40', '147', 'Conferencias Sectoriales', 'La Conferencia Sectorial reúne, como Presidente, a:', 'El miembro del Gobierno que, en representación de la Administración General del Estado, resulte competente por razón de la materia.', ['El Presidente del Gobierno.', 'El Ministro de Hacienda y Administraciones Públicas, en todo caso.', 'Un Consejero designado de común acuerdo por las Comunidades Autónomas.'], 'La Conferencia Sectorial [...] reúne, como Presidente, al miembro del Gobierno que, en representación de la Administración General del Estado, resulte competente por razón de la materia.'],
['l40', '148', 'Funciones de las Conferencias Sectoriales', 'Las Conferencias Sectoriales pueden ejercer funciones:', 'Consultivas, decisorias o de coordinación orientadas a alcanzar acuerdos sobre materias comunes.', ['Exclusivamente consultivas.', 'Consultivas y sancionadoras.', 'Decisorias y de control económico de las Comunidades Autónomas.'], 'Las Conferencias Sectoriales pueden ejercer funciones consultivas, decisorias o de coordinación orientadas a alcanzar acuerdos sobre materias comunes.'],
['l40', '153', 'Comisiones Bilaterales de Cooperación', 'Las Comisiones Bilaterales de Cooperación reúnen:', 'Por un número igual de representantes, a miembros del Gobierno, en representación de la Administración General del Estado, y miembros del Consejo de Gobierno de la Comunidad Autónoma o representantes de la Ciudad de Ceuta o de la Ciudad de Melilla.', ['Por un número proporcional a la población, a representantes del Gobierno y de la Comunidad Autónoma.', 'A miembros del Gobierno y a representantes de las Entidades Locales de la Comunidad Autónoma.', 'A los Delegados y Subdelegados del Gobierno con los Consejeros de la Comunidad Autónoma.'], 'Reúnen, por un número igual de representantes, a miembros del Gobierno, en representación de la Administración General del Estado, y miembros del Consejo de Gobierno de la Comunidad Autónoma o representantes de la Ciudad de Ceuta o de la Ciudad de Melilla.'],
['l19', '7', 'Información de relevancia jurídica', 'Las Administraciones Públicas publicarán los Anteproyectos de Ley y los proyectos de Decretos Legislativos cuya iniciativa les corresponda cuando se soliciten los dictámenes a los órganos consultivos. En el caso en que no sea preceptivo ningún dictamen, la publicación se realizará:', 'En el momento de su aprobación.', ['Una vez publicados en el «Boletín Oficial del Estado».', 'A los quince días de su aprobación.', 'Cuando lo solicite un ciudadano.'], 'En el caso en que no sea preceptivo ningún dictamen la publicación se realizará en el momento de su aprobación.'],
['l19', '13', 'Información pública', 'Se entiende por información pública:', 'Los contenidos o documentos, cualquiera que sea su formato o soporte, que obren en poder de alguno de los sujetos incluidos en el ámbito de aplicación del título y que hayan sido elaborados o adquiridos en el ejercicio de sus funciones.', ['Solo los documentos en soporte electrónico que hayan sido elaborados por el sujeto obligado.', 'Exclusivamente los contenidos publicados en el Portal de la Transparencia.', 'Los documentos elaborados por el sujeto obligado, con exclusión de los adquiridos en el ejercicio de sus funciones.'], 'Se entiende por información pública los contenidos o documentos, cualquiera que sea su formato o soporte, que obren en poder de alguno de los sujetos incluidos en el ámbito de aplicación de este título y que hayan sido elaborados o adquiridos en el ejercicio de sus funciones.'],
['l19', '25', 'Ámbito de aplicación del buen gobierno', 'A efectos del título de buen gobierno, se considerarán altos cargos los que tengan tal consideración en aplicación de la normativa en materia de:', 'Conflictos de intereses.', ['Función pública.', 'Contratación del sector público.', 'Incompatibilidades del personal funcionario.'], 'A estos efectos, se considerarán altos cargos los que tengan tal consideración en aplicación de la normativa en materia de conflictos de intereses.'],
['l19', '26', 'Principios de buen gobierno', 'Entre los principios generales de buen gobierno, las personas comprendidas en su ámbito de aplicación actuarán con transparencia en la gestión de los asuntos públicos, de acuerdo con los principios de:', 'Eficacia, economía y eficiencia y con el objetivo de satisfacer el interés general.', ['Legalidad, jerarquía y publicidad, con el objetivo de proteger el orden público.', 'Eficacia, celeridad y proporcionalidad, con el objetivo de reducir el gasto público.', 'Economía, imparcialidad y neutralidad, con el objetivo de garantizar la igualdad.'], 'Actuarán con transparencia en la gestión de los asuntos públicos, de acuerdo con los principios de eficacia, economía y eficiencia y con el objetivo de satisfacer el interés general.'],
['l19', '34', 'Fines del Consejo de Transparencia y Buen Gobierno', 'El Consejo de Transparencia y Buen Gobierno tiene por finalidad:', 'Promover la transparencia de la actividad pública, velar por el cumplimiento de las obligaciones de publicidad, salvaguardar el ejercicio del derecho de acceso a la información pública y garantizar la observancia de las disposiciones de buen gobierno.', ['Supervisar la ejecución presupuestaria de todas las Administraciones Públicas y sancionar su incumplimiento.', 'Resolver los recursos contencioso-administrativos en materia de acceso a la información pública.', 'Fiscalizar la gestión económica de los altos cargos y exigirles responsabilidad penal.'], 'El Consejo de Transparencia y Buen Gobierno tiene por finalidad promover la transparencia de la actividad pública, velar por el cumplimiento de las obligaciones de publicidad, salvaguardar el ejercicio de derecho de acceso a la información pública y garantizar la observancia de las disposiciones de buen gobierno.'],
['l19', '39', 'Régimen jurídico del Consejo de Transparencia', 'El Consejo de Transparencia y Buen Gobierno elaborará anualmente un anteproyecto de presupuesto con la estructura que establezca:', 'El Ministerio de Hacienda y Administraciones Públicas, para su elevación al Gobierno y su posterior integración en los Presupuestos Generales del Estado.', ['El Congreso de los Diputados, para su aprobación directa por el Pleno.', 'El Tribunal de Cuentas, para su elevación a las Cortes Generales.', 'El Ministerio de la Presidencia, para su remisión al Consejo de Estado.'], 'Anualmente elaborará un anteproyecto de presupuesto con la estructura que establezca el Ministerio de Hacienda y Administraciones Públicas para su elevación al Gobierno y su posterior integración en los Presupuestos Generales del Estado.'],
['l19', '40', 'Relaciones con las Cortes Generales', 'El Consejo de Transparencia y Buen Gobierno elevará a las Cortes Generales:', 'Anualmente, una memoria sobre el desarrollo de sus actividades y sobre el grado de cumplimiento de las disposiciones establecidas en la Ley.', ['Semestralmente, un informe sobre las reclamaciones resueltas.', 'Cada dos años, una memoria sobre el grado de cumplimiento de la Ley.', 'Anualmente, un dictamen sobre los anteproyectos de ley en materia de transparencia.'], 'El Consejo de Transparencia y Buen Gobierno elevará anualmente a las Cortes Generales una memoria sobre el desarrollo de sus actividades y sobre el grado de cumplimiento de las disposiciones establecidas en esta Ley.'],
['l19', '9', 'Control de la publicidad activa', 'El incumplimiento reiterado de las obligaciones de publicidad activa tendrá la consideración de infracción:', 'Grave, a los efectos de aplicación a sus responsables del régimen disciplinario previsto en la correspondiente normativa reguladora.', ['Leve, a los efectos del régimen disciplinario correspondiente.', 'Muy grave, a los efectos del régimen disciplinario correspondiente.', 'No constituye infracción, sino una irregularidad que solo da lugar a un requerimiento.'], 'El incumplimiento reiterado de las obligaciones de publicidad activa reguladas en este capítulo tendrá la consideración de infracción grave a los efectos de aplicación a sus responsables del régimen disciplinario previsto en la correspondiente normativa reguladora.'],
['l19', '17', 'Solicitud de acceso a la información', 'En el procedimiento de acceso a la información pública, el solicitante:', 'No está obligado a motivar su solicitud de acceso a la información.', ['Está obligado a motivar su solicitud de acceso a la información.', 'Puede presentar la solicitud de forma anónima.', 'Debe acreditar un interés legítimo en la información solicitada.'], 'El solicitante no está obligado a motivar su solicitud de acceso a la información.'],
['l19', '37', 'Presidente del Consejo de Transparencia y Buen Gobierno', 'El Presidente del Consejo de Transparencia y Buen Gobierno será nombrado por un período:', 'No renovable de cinco años, mediante Real Decreto, a propuesta del titular del Ministerio de Hacienda y Administraciones Públicas.', ['Renovable de cinco años, mediante Real Decreto, a propuesta del Presidente del Gobierno.', 'No renovable de seis años, mediante Real Decreto, a propuesta del Ministro de Justicia.', 'Renovable de cuatro años, por acuerdo del Congreso de los Diputados.'], 'El Presidente del Consejo de Transparencia y Buen Gobierno será nombrado por un período no renovable de cinco años mediante Real Decreto, a propuesta del titular del Ministerio de Hacienda y Administraciones Públicas.'],
['rd', '9', 'Formación', 'La formación suficiente y adecuada en materia preventiva del personal de la Guardia Civil será garantizada por:', 'La Dirección General de la Guardia Civil.', ['La Secretaría de Estado de Seguridad.', 'El Servicio de Prevención.', 'La Jefatura de Enseñanza.'], 'La Dirección General de la Guardia Civil garantizará una formación suficiente y adecuada en materia preventiva.'],
['rd', '10', 'Protección de la maternidad', 'La evaluación de los riesgos deberá comprender la determinación de la naturaleza, el grado y la duración de la exposición de la mujer en situación de embarazo o parto reciente a:', 'Agentes, procedimientos o condiciones de trabajo que puedan influir negativamente en su salud o en la del feto, en cualquier actividad susceptible de presentar un riesgo específico.', ['Únicamente agentes químicos y biológicos, en actividades de riesgo especial.', 'Servicios nocturnos y servicios de armas, sin otras condiciones de trabajo.', 'Cualquier actividad operativa, con exclusión de las actividades administrativas.'], 'La evaluación de los riesgos [...] deberá comprender la determinación de la naturaleza, el grado y la duración de la exposición de la mujer en situación de embarazo o parto reciente a agentes, procedimientos o condiciones de trabajo que puedan influir negativamente en su salud o en la del feto, en cualquier actividad susceptible de presentar un riesgo específico.'],
['rd', '11', 'Obligaciones de la Administración', 'Los órganos administrativos comprendidos en el ámbito de aplicación del Real Decreto deberán proporcionar al personal:', 'Equipos de protección individual adecuados para el desempeño de sus funciones y velar por el uso efectivo de éstos cuando, por la naturaleza de las misiones desempeñadas, sean necesarios.', ['Equipos de protección individual únicamente cuando el interesado los solicite por escrito.', 'Equipos de protección individual, sin obligación de velar por su uso efectivo.', 'Equipos de protección colectiva, con exclusión de los individuales.'], 'Deberán proporcionar al personal incluido en el ámbito de aplicación de este real decreto equipos de protección individual adecuados para el desempeño de sus funciones y velar por el uso efectivo de éstos cuando, por la naturaleza de las misiones desempeñadas, sean necesarios.'],
['rd', '1', 'Objeto', 'El objeto del Real Decreto 179/2005 es promover la seguridad y la salud en el trabajo del personal:', 'Del Cuerpo de la Guardia Civil y de los miembros de las Fuerzas Armadas que presten servicios en unidades, centros y organismos de la Dirección General de la Guardia Civil.', ['Exclusivamente del Cuerpo de la Guardia Civil.', 'Del Cuerpo de la Guardia Civil y del Cuerpo Nacional de Policía.', 'De los guardias civiles en servicio activo, con exclusión de los destinados en servicios administrativos.'], 'El objeto de este real decreto es promover la seguridad y la salud en el trabajo del personal del Cuerpo de la Guardia Civil y de los miembros de las Fuerzas Armadas que presten servicios en unidades, centros y organismos de la Dirección General de la Guardia Civil.'],
['rd', '3', 'Objetivos', 'Las medidas que se adopten en aplicación del Real Decreto tendrán como objetivo principal:', 'La promoción de la mejora de las condiciones del servicio.', ['La reducción de la siniestralidad estadística del Cuerpo.', 'La adaptación de la estructura orgánica de la Dirección General.', 'El control de las bajas por enfermedad profesional.'], 'Tendrán como objetivo principal [...] la promoción de la mejora de las condiciones del servicio y tratarán de elevar el nivel de protección de la seguridad y la salud del personal al que se dirigen.'],
['rd', '4', 'Plan de prevención', 'Los instrumentos esenciales para la gestión y aplicación del plan de prevención de riesgos laborales en la Guardia Civil son:', 'La evaluación de riesgos laborales y la planificación de la actividad preventiva.', ['La vigilancia de la salud y la formación del personal.', 'La información al personal y la participación de las asociaciones profesionales.', 'La inspección y el control interno y externo.'], 'Los instrumentos esenciales para la gestión y aplicación del plan de prevención de riesgos son la evaluación de riesgos laborales y la planificación de la actividad preventiva.'],
['rd', '6', 'Vigilancia de la salud', 'Los datos que deriven de la vigilancia de la salud del personal de la Guardia Civil:', 'No podrán ser usados con fines discriminatorios ni en perjuicio de la persona afectada.', ['Podrán ser usados para determinar el destino del personal, si lo autoriza el mando.', 'Serán comunicados al mando de la unidad para la planificación de los servicios.', 'Podrán cederse a las asociaciones profesionales representativas.'], 'Esta vigilancia se llevará a cabo respetando la dignidad de la persona, la confidencialidad de toda la información relacionada con el estado de salud y garantizando que los datos que deriven de esa vigilancia no podrán ser usados con fines discriminatorios ni en perjuicio de la persona afectada.'],
['rd', '7', 'Principio de información', 'La información sobre los riesgos de la función que realiza el personal de la Guardia Civil y las medidas adoptadas para su prevención estará contenida en:', 'Los manuales de los servicios, instrucciones y órdenes impartidas.', ['El Boletín Oficial de la Guardia Civil exclusivamente.', 'Las circulares del Servicio de Prevención.', 'La memoria anual de los órganos de prevención.'], 'Esta información estará contenida en los manuales de los servicios, instrucciones y órdenes impartidas, cuyo contenido deberá ser conocido por los miembros del Cuerpo de la Guardia Civil hasta el nivel necesario para asegurar la prevención.'],
['rd', '12', 'Obligaciones del personal', 'El personal incluido en el ámbito de aplicación del Real Decreto deberá velar, según sus posibilidades y mediante el cumplimiento de las medidas de prevención adoptadas, por:', 'Su propia seguridad y salud en el desempeño de sus funciones y por la de aquellas otras personas a las que pueda afectar su actividad profesional, a causa de sus actos y omisiones.', ['Su propia seguridad y salud, sin responsabilidad respecto de terceras personas.', 'La seguridad de sus subordinados, únicamente cuando ejerzan mando.', 'La seguridad de las instalaciones, con exclusión de la salud del personal.'], 'Deberá velar [...] por su propia seguridad y salud en el desempeño de sus funciones y por la de aquellas otras personas a las que pueda afectar su actividad profesional, a causa de sus actos y omisiones, de conformidad con su formación y las instrucciones recibidas.'],
['rd', '15', 'Inspección y control', 'Las funciones de inspección y control externo de las actividades de los órganos de prevención de la Guardia Civil corresponden a:', 'La Inspección de Personal y Servicios de Seguridad de la Secretaría de Estado de Seguridad.', ['La Inspección de Trabajo y Seguridad Social.', 'El Servicio de Prevención de la Dirección General de la Guardia Civil.', 'La Jefatura de Personal de la Dirección General de la Guardia Civil.'], 'La Inspección de Personal y Servicios de Seguridad de la Secretaría de Estado de Seguridad realizará las funciones de inspección y control externo de las actividades de los órganos citados en el párrafo anterior.'],
['lo3', '11', 'Transparencia e información al afectado', 'La información básica que el responsable del tratamiento debe facilitar al afectado cuando los datos sean obtenidos del propio afectado deberá contener, al menos:', 'La identidad del responsable del tratamiento y de su representante, en su caso, la finalidad del tratamiento y la posibilidad de ejercer los derechos establecidos en los artículos 15 a 22 del Reglamento (UE) 2016/679.', ['La identidad del responsable, el plazo de conservación de los datos y los destinatarios de los mismos.', 'La identidad del delegado de protección de datos, la base jurídica y la finalidad del tratamiento.', 'La finalidad del tratamiento, las categorías de datos tratados y las fuentes de las que proceden.'], 'La información básica [...] deberá contener, al menos: a) La identidad del responsable del tratamiento y de su representante, en su caso. b) La finalidad del tratamiento. c) La posibilidad de ejercer los derechos establecidos en los artículos 15 a 22 del Reglamento (UE) 2016/679.'],
['lo3', '34', 'Designación de un delegado de protección de datos', 'Los responsables y encargados del tratamiento deberán designar, en todo caso, un delegado de protección de datos cuando se trate de:', 'Los colegios profesionales y sus consejos generales.', ['Las asociaciones y fundaciones sin ánimo de lucro.', 'Las comunidades de propietarios.', 'Los empresarios individuales y profesionales liberales.'], 'Los responsables y encargados del tratamiento deberán designar un delegado de protección de datos [...] cuando se trate de las siguientes entidades: a) Los colegios profesionales y sus consejos generales.']
];

const L = 'ABCD';
const out = Q.map((q, i) => {
  const [n, art, mat, enun, ok, ds, cita, neg] = q;
  const pos = (i * 3 + 1) % 4;                    // reparto equilibrado de la letra correcta
  const ops = ds.slice(); ops.splice(pos, 0, ok);
  const letra = L[pos];
  const refn = `art. ${art} de la ${N[n][0]}`;
  const porque = neg ? `La opción ${letra} es la incorrecta porque ${neg}` : `Las demás opciones no se ajustan al texto del precepto.`;
  return {
    id: '11-' + (174 + i),
    pregunta: `${N[n][1]}. ${mat}. ${enun}`,
    opciones: ops, correcta: pos,
    explicacion: `<span class="ex-resp">Respuesta correcta: <b>${letra}</b> · <mark class="ex-key">${ok}</mark></span> El <span class="ref-norma">${refn}</span> dispone: <span class="ref-concepto">"${cita}"</span>. ${porque}`,
    apartado: NOMBRE[n] };
});
let s = fs.readFileSync(F, 'utf8');
const nuevos = out.filter(o => !s.includes(`"id":"${o.id}"`));
if (!nuevos.length) { console.log('nada que añadir'); process.exit(0); }
const i0 = s.indexOf('{"id":"11-173"');
if (i0 < 0) throw new Error('11-173 no encontrado');
let d = 0, inS = false, esc = false, j = i0;
for (; j < s.length; j++) { const c = s[j]; if (inS) { if (esc) esc = false; else if (c === '\\') esc = true; else if (c === '"') inS = false; continue; } if (c === '"') inS = true; else if (c === '{') d++; else if (c === '}') { d--; if (d === 0) break; } }
const ins = nuevos.map(o => ',' + JSON.stringify(o)).join('');
s = s.slice(0, j + 1) + ins + s.slice(j + 1);
fs.writeFileSync(F, s);
const cnt = {}; out.forEach(o => cnt[L[o.correcta]] = (cnt[L[o.correcta]] || 0) + 1);
console.log('añadidas', nuevos.length, 'ids', nuevos[0].id, '→', nuevos[nuevos.length - 1].id, 'letras', cnt);
