# -*- coding: utf-8 -*-
# Genera las 50 preguntas IA del Tema 14 (texto oficial: LO 3/1981 y Reglamento del Defensor del Pueblo)
import json, random, sys, re

LO = 'LO'; RG = 'RG'
AP = {LO: 'Ley Orgánica 3/1981, de 6 de abril, del Defensor del Pueblo',
      RG: 'Reglamento de Organización y Funcionamiento del Defensor del Pueblo'}
PRE = {LO: 'LO 3/1981, del Defensor del Pueblo, art. ', RG: 'Reglamento del Defensor del Pueblo, art. '}
REF = {LO: ('art. {a} de la LO 3/1981, del Defensor del Pueblo', 'El '),
       RG: ('art. {a} del Reglamento de Organización y Funcionamiento del Defensor del Pueblo', 'El ')}
DIF = {'f': ('facil', 'Fácil'), 'm': ('media', 'Media'), 'd': ('dificil', 'Difícil')}

# (norma, art, dif, enunciado, correcta, [3 distractores], cita literal, por qué fallan las otras)
Q = [
# ---------- FÁCILES (10)
(LO, '4.1', 'f', '¿Quiénes acreditan conjuntamente con sus firmas el nombramiento del Defensor del Pueblo, que se publicará en el «Boletín Oficial del Estado»?',
 'Los Presidentes del Congreso y del Senado.',
 ['El Presidente del Gobierno y el Presidente del Congreso.', 'Las Mesas de ambas Cámaras reunidas conjuntamente.', 'El Presidente de la Comisión Mixta Congreso-Senado.'],
 'Los Presidentes del Congreso y del Senado acreditarán conjuntamente con sus firmas el nombramiento del Defensor del Pueblo que se publicará en el «Boletín Oficial del Estado»',
 'las Mesas de ambas Cámaras reunidas conjuntamente intervienen en la toma de posesión (art. 4.2), no en la acreditación del nombramiento; el Presidente del Gobierno y el de la Comisión Mixta no firman el nombramiento.'),
(LO, '8.3', 'f', 'El nombramiento de los Adjuntos del Defensor del Pueblo será publicado en:',
 'El «Boletín Oficial del Estado».',
 ['Únicamente en el Boletín Oficial de las Cortes Generales.', 'El Diario de Sesiones del Congreso de los Diputados.', 'No se publica: basta la comunicación a las Cámaras.'],
 'El nombramiento de los Adjuntos será publicado en el «Boletín Oficial del Estado»',
 'la Ley exige publicación en el BOE; no basta un boletín interno de las Cámaras ni la mera comunicación.'),
(LO, '16.1', 'f', 'La correspondencia dirigida al Defensor del Pueblo y remitida desde cualquier centro de detención, internamiento o custodia de las personas:',
 'No podrá ser objeto de censura de ningún tipo.',
 ['Podrá ser censurada previa autorización judicial.', 'Podrá ser revisada por el director del centro antes de su envío.', 'Solo podrá ser censurada durante los estados de excepción o de sitio.'],
 'La correspondencia dirigida al Defensor del Pueblo y que sea remitida desde cualquier centro de detención, internamiento o custodia de las personas no podrá ser objeto de censura de ningún tipo',
 'la prohibición es absoluta («de ningún tipo»): no cabe censura judicial, administrativa ni por razón de estados excepcionales.'),
(LO, '26', 'f', 'El Defensor del Pueblo podrá ejercitar de oficio la acción de responsabilidad contra todas las autoridades, funcionarios y agentes civiles del orden gubernativo o administrativo, incluso local:',
 'Sin que sea necesaria en ningún caso la previa reclamación por escrito.',
 ['Previa reclamación por escrito dirigida al superior jerárquico.', 'Solo si lo solicita por escrito el interesado.', 'Solo previa autorización de la Comisión Mixta Congreso-Senado.'],
 'El Defensor del Pueblo podrá, de oficio, ejercitar la acción de responsabilidad contra todas las autoridades, funcionarios y agentes civiles del orden gubernativo o administrativo, incluso local, sin que sea necesaria en ningún caso la previa reclamación por escrito',
 'el art. 26 lo permite «de oficio» y elimina cualquier reclamación previa por escrito o autorización de otro órgano.'),
(LO, '27', 'f', 'Los gastos efectuados o perjuicios materiales causados a los particulares que no hayan promovido la queja al ser llamados a informar por el Defensor del Pueblo serán satisfechos:',
 'Con cargo al presupuesto del Defensor del Pueblo, una vez justificados debidamente.',
 ['Con cargo al presupuesto del Ministerio de Justicia, previa solicitud.', 'Por el particular que promovió la queja.', 'Con cargo al presupuesto de la Administración investigada, sin necesidad de justificarlos.'],
 'serán correspondidos con cargo a su presupuesto una vez justificados debidamente',
 'se pagan con cargo al presupuesto del propio Defensor y solo una vez justificados; no los asume el promotor de la queja ni otro departamento.'),
(LO, '11.2', 'f', 'Si las Cortes Generales no se encuentran reunidas, hubieran sido disueltas o hubiera expirado su mandato, el Defensor del Pueblo se dirigirá a:',
 'Las Diputaciones Permanentes de las Cámaras.',
 ['La Comisión Mixta Congreso-Senado.', 'Las Mesas del Congreso y del Senado.', 'Los Presidentes del Congreso y del Senado.'],
 'En las situaciones previstas en el apartado anterior, el Defensor del Pueblo se dirigirá a las Diputaciones Permanentes de las Cámaras',
 'la Comisión Mixta, las Mesas y los Presidentes son interlocutores en situación normal; en periodos sin Cortes reunidas la Ley prevé las Diputaciones Permanentes.'),
(RG, '24', 'f', '¿En cuántos servicios está estructurada la Secretaría General del Defensor del Pueblo?',
 'En dos servicios: el de Régimen Económico y el de Régimen Interior, Estudios, Documentación y Publicaciones.',
 ['En tres servicios: Económico, Interior y Registro.', 'En cuatro servicios, uno por cada Sección existente.', 'En un único servicio auxiliado por un Asesor.'],
 'La Secretaría General estará estructurada en dos servicios: el de Régimen Económico y el de Régimen Interior, Estudios, Documentación y Publicaciones',
 'son exactamente dos servicios; el Asesor solo «podrá auxiliar» al Secretario general (art. 24), y las Secciones cuelgan de los servicios.'),
(RG, '42', 'f', 'El régimen de contratación y de adquisición en general en el Defensor del Pueblo será:',
 'El que rija para las Cortes Generales.',
 ['El de la Administración General del Estado.', 'El que fije libremente la Junta de Coordinación y Régimen Interior.', 'El que determine el Defensor del Pueblo mediante instrucciones internas.'],
 'El régimen de contratación y de adquisición en general en el Defensor del Pueblo será el que rija para las Cortes Generales',
 'el Defensor se asimila a las Cortes Generales (igual que en contabilidad, intervención y presupuesto), no a la Administración del Estado ni a normas propias.'),
(LO, '6.4', 'f', 'Las reglas de ausencia de mandato imperativo, inviolabilidad y no detención del Defensor del Pueblo son aplicables:',
 'También a los Adjuntos del Defensor del Pueblo, en el cumplimiento de sus funciones.',
 ['Solo al Defensor del Pueblo, nunca a los Adjuntos.', 'A los Adjuntos únicamente cuando ejerzan funciones por delegación.', 'A los Adjuntos y a los asesores de la Institución.'],
 'Las anteriores reglas serán aplicables a los Adjuntos del Defensor del Pueblo en el cumplimiento de sus funciones',
 'se extienden a los Adjuntos en todo el cumplimiento de sus funciones, no solo por delegación, y no alcanzan a los asesores.'),
(RG, '2.4', 'f', 'Las reglas de inviolabilidad y no detención del Defensor del Pueblo constarán expresamente en el documento oficial que acredite su personalidad y cargo, que expedirán:',
 'Las Cortes Generales.',
 ['El Ministerio de Justicia.', 'El Tribunal Supremo.', 'El Presidente del Gobierno.'],
 'Los anteriores extremos constarán expresamente en el documento oficial que expedirán las Cortes Generales acreditando su personalidad y cargo',
 'el Defensor es alto comisionado de las Cortes Generales, que son quienes expiden el documento acreditativo; el Gobierno y los tribunales no intervienen.'),
# ---------- MEDIAS (25)
(LO, '2.6', 'm', 'Según el art. 2.6, designado el Defensor del Pueblo, ¿qué órgano otorga la conformidad previa al nombramiento de los Adjuntos que él proponga?',
 'La Comisión Mixta Congreso-Senado.',
 ['El Pleno del Congreso, por tres quintas partes.', 'Las Mesas de ambas Cámaras reunidas conjuntamente.', 'El Pleno del Senado, por mayoría absoluta.'],
 'Designado el Defensor del Pueblo se reunirá de nuevo la Comisión Mixta Congreso-Senado para otorgar su conformidad previa al nombramiento de los adjuntos que le sean propuestos por aquél',
 'las mayorías de tres quintas y la absoluta son las de la elección del Defensor (art. 2.4 y 2.5), no las de la conformidad de los Adjuntos; las Mesas solo reciben la toma de posesión.'),
(LO, '5.4', 'm', 'En los casos de muerte, cese o incapacidad temporal o definitiva del Defensor del Pueblo, y en tanto no procedan las Cortes Generales a una nueva designación, desempeñarán sus funciones interinamente:',
 'Los Adjuntos al Defensor del Pueblo, en su propio orden.',
 ['El Presidente del Congreso de los Diputados.', 'La Comisión Mixta Congreso-Senado.', 'El Secretario General de la Institución.'],
 'desempeñarán sus funciones, interinamente, en su propio orden, los Adjuntos al Defensor del Pueblo',
 'la sustitución interina corresponde a los Adjuntos por su orden (Primero y Segundo); ni el Presidente del Congreso, ni la Comisión Mixta, ni el Secretario General asumen las funciones.'),
(LO, '6.3', 'm', 'En los demás casos, y mientras permanezca en el ejercicio de sus funciones, el Defensor del Pueblo no podrá ser detenido ni retenido sino en caso de:',
 'Flagrante delito.',
 ['Delito doloso castigado con pena grave.', 'Cualquier delito, con autorización del Presidente del Congreso.', 'Flagrante delito y, además, con autorización de la Comisión Mixta.'],
 'el Defensor del Pueblo no podrá ser detenido ni retenido sino en caso de flagrante delito, correspondiendo la decisión sobre su inculpación, prisión, procesamiento y juicio exclusivamente a la Sala de lo Penal del Tribunal Supremo',
 'la única excepción es el flagrante delito, sin gravedad mínima ni autorizaciones previas; después decide en exclusiva la Sala de lo Penal del Tribunal Supremo.'),
(LO, '7.1', 'm', 'La condición de Defensor del Pueblo es incompatible con la afiliación a un partido político o el desempeño de funciones ________ en un partido político, sindicato, asociación o fundación, y con el empleo al servicio de los mismos.',
 'directivas',
 ['consultivas', 'honoríficas', 'representativas'],
 'con la afiliación a un partido político o el desempeño de funciones directivas en un partido político o en un sindicato, asociación o fundación, y con el empleo al servicio de los mismos',
 'la incompatibilidad se refiere a funciones directivas; «mandato representativo» es otra incompatibilidad distinta de la misma lista.'),
(LO, '8.4', 'm', '¿Qué artículos de la LO 3/1981, aplicables al Defensor del Pueblo, serán también de aplicación a los Adjuntos?',
 'Los artículos tercero, sexto y séptimo.',
 ['Los artículos tercero, cuarto y quinto.', 'Los artículos segundo, sexto y séptimo.', 'Los artículos sexto, séptimo y octavo.'],
 'A los Adjuntos les será de aplicación lo dispuesto para el Defensor del Pueblo en los artículos tercero, sexto y séptimo de la presente Ley',
 'son el 3.º (requisitos de elegibilidad), el 6.º (prerrogativas) y el 7.º (incompatibilidades); el 2.º (elección), el 4.º (nombramiento y posesión) y el 5.º (cese) no se aplican por esta vía.'),
(LO, '9.1', 'm', 'El Defensor del Pueblo podrá iniciar y proseguir de oficio o a petición de parte cualquier investigación sobre los actos y resoluciones de la Administración pública, a la luz del artículo 103.1 de la Constitución y el respeto debido a los Derechos proclamados en su Título:',
 'Primero.',
 ['Preliminar.', 'Segundo.', 'Tercero.'],
 'a la luz de lo dispuesto en el artículo ciento tres, uno, de la Constitución, y el respeto debido a los Derechos proclamados en su Título primero',
 'el Título I de la Constitución recoge los derechos y deberes fundamentales, que es lo que el Defensor supervisa; los demás títulos tratan otras materias.'),
(LO, '10.1', 'm', 'Sobre quién puede dirigirse al Defensor del Pueblo, señale la INCORRECTA:',
 'El internamiento en un centro penitenciario o de reclusión constituye un impedimento para dirigirse al Defensor del Pueblo.',
 ['Puede dirigirse toda persona natural o jurídica que invoque un interés legítimo, sin restricción alguna.', 'La nacionalidad, la residencia y el sexo no pueden constituir impedimento.', 'La minoría de edad y la incapacidad legal del sujeto no pueden constituir impedimento.'],
 'No podrán constituir impedimento para ello la nacionalidad, residencia, sexo, minoría de edad, la incapacidad legal del sujeto, el internamiento en un centro penitenciario o de reclusión o, en general, cualquier relación especial de sujeción o dependencia de una Administración o Poder público',
 'el internamiento penitenciario figura precisamente entre las circunstancias que NO pueden ser impedimento; las otras tres opciones reproducen correctamente el art. 10.1.'),
(LO, '11.3', 'm', 'La declaración de los estados de excepción o de sitio:',
 'No interrumpirá la actividad del Defensor del Pueblo ni el derecho de los ciudadanos a acceder al mismo, sin perjuicio de lo dispuesto en el artículo 55 de la Constitución.',
 ['Suspenderá la actividad del Defensor del Pueblo mientras dure la situación.', 'Suspenderá únicamente el derecho de los ciudadanos a acceder al Defensor del Pueblo.', 'Interrumpirá la actividad del Defensor, pero no el derecho de acceso de los ciudadanos.'],
 'La declaración de los estados de excepción o de sitio no interrumpirán la actividad del Defensor del Pueblo, ni el derecho de los ciudadanos de acceder al mismo, sin perjuicio de lo dispuesto en el artículo cincuenta y cinco de la Constitución',
 'ni la actividad ni el acceso se interrumpen; la única salvedad es lo previsto en el art. 55 CE sobre suspensión de derechos.'),
(LO, '12.2', 'm', 'En la supervisión de la actividad de las Comunidades Autónomas, los órganos similares al Defensor del Pueblo de las mismas:',
 'Coordinarán sus funciones con las del Defensor del Pueblo, que podrá solicitar su cooperación.',
 ['Ejercerán la supervisión en exclusiva, sin intervención del Defensor del Pueblo.', 'Quedarán subordinados jerárquicamente al Defensor del Pueblo.', 'Solo podrán relacionarse con él a través de la Comisión Mixta Congreso-Senado.'],
 'los órganos similares de las Comunidades Autónomas coordinarán sus funciones con las del Defensor del Pueblo y éste podrá solicitar su cooperación',
 'la relación es de coordinación y cooperación (no exclusión, jerarquía ni intermediación de la Comisión Mixta).'),
(LO, '17.2', 'm', 'Respecto de las quejas sobre las que esté pendiente resolución judicial, el Defensor del Pueblo:',
 'No entrará en su examen individual, sin que ello impida la investigación sobre los problemas generales planteados en las quejas.',
 ['Las examinará con carácter preferente.', 'Las remitirá al Ministerio Fiscal para su investigación.', 'Las rechazará y tampoco podrá investigar los problemas generales que planteen.'],
 'El Defensor del Pueblo no entrará en el examen individual de aquellas quejas sobre las que esté pendiente resolución judicial y lo suspenderá si, iniciada su actuación, se interpusiere por persona interesada demanda o recurso ante las Tribunales ordinarios o el Tribunal Constitucional. Ello no impedirá, sin embargo, la investigación sobre los problemas generales planteados en las quejas presentadas',
 'solo se excluye el examen individual; los problemas generales sí pueden investigarse, y la remisión al Fiscal es para quejas sobre la Administración de Justicia (art. 13).'),
(LO, '19.3', 'm', 'Al Defensor del Pueblo no podrá negársele el acceso a ningún expediente o documentación administrativa relacionada con la actividad o servicio objeto de la investigación, sin perjuicio de lo que se dispone en el artículo:',
 'Veintidós (documentos reservados).',
 ['Veintiuno.', 'Veintitrés.', 'Dieciocho.'],
 'no podrá negársele el acceso a ningún expediente o documentación administrativa o que se encuentre relacionada con la actividad o servicio objeto de la investigación, sin perjuicio de lo que se dispone en el artículo veintidós de esta Ley',
 'la salvedad se remite al art. 22, que regula los documentos reservados o secretos; los demás artículos citados tratan otras materias.'),
(LO, '20.2', 'm', 'El afectado responderá por escrito, en el plazo que se le haya fijado, que en ningún caso será inferior a diez días, pudiendo ser prorrogado a instancia de parte:',
 'Por la mitad del concedido.',
 ['Por otro plazo igual al concedido.', 'Hasta un máximo de un mes.', 'Por cinco días más, en todo caso.'],
 'en el plazo que se le haya fijado, que en ningún caso será inferior a diez días, pudiendo ser prorrogado, a instancia de parte, por la mitad del concedido',
 'la prórroga es proporcional (la mitad del plazo concedido), no fija ni igual al plazo inicial.'),
(LO, '21', 'm', 'El superior jerárquico u Organismo que prohíba al funcionario a sus órdenes responder a la requisitoria del Defensor del Pueblo o entrevistarse con él deberá manifestarlo:',
 'Por escrito, debidamente motivado, dirigido al funcionario y al propio Defensor del Pueblo.',
 ['Verbalmente al funcionario, sin necesidad de motivarlo.', 'Por escrito dirigido únicamente al funcionario.', 'Mediante comunicación a la Comisión Mixta Congreso-Senado.'],
 'deberá manifestarlo por escrito, debidamente motivado, dirigido al funcionario y al propio Defensor del Pueblo. El Defensor del Pueblo dirigirá en adelante cuantas actuaciones investigadoras sean necesarias al referido superior jerárquico',
 'la prohibición exige forma escrita, motivación y dos destinatarios (funcionario y Defensor); después el Defensor se dirige ya al superior.'),
(LO, '22.2', 'm', 'Las investigaciones que realice el Defensor del Pueblo y el personal dependiente del mismo, así como los trámites procedimentales, se verificarán dentro de la más absoluta reserva, sin perjuicio de:',
 'Las consideraciones que el Defensor del Pueblo considere oportuno incluir en sus informes a las Cortes Generales.',
 ['Lo que acuerde el Ministro del Departamento afectado.', 'La publicidad que exija el interesado.', 'Lo que decida la Comisión Mixta en cada caso.'],
 'se verificarán dentro de la más absoluta reserva, tanto con respecto a los particulares como a las dependencias y demás Organismos públicos, sin perjuicio de las consideraciones que el Defensor del Pueblo considere oportuno incluir en sus informes a las Cortes Generales',
 'la única excepción a la reserva son las consideraciones que el propio Defensor decida incluir en sus informes a las Cortes.'),
(LO, '28.3', 'm', 'Si las actuaciones se hubiesen realizado con ocasión de servicios prestados por particulares en virtud de acto administrativo habilitante, el Defensor del Pueblo podrá:',
 'Instar de las autoridades administrativas competentes el ejercicio de sus potestades de inspección y sanción.',
 ['Sancionar directamente a los particulares.', 'Anular el acto administrativo habilitante.', 'Suspender por sí mismo la prestación del servicio.'],
 'el Defensor del Pueblo podrá instar de las autoridades administrativas competentes el ejercicio de sus potestades de inspección y sanción',
 'el Defensor no es competente para modificar o anular actos ni para sancionar (art. 28.1): solo puede instar a la autoridad competente.'),
(LO, '30.2', 'm', 'Si formuladas sus recomendaciones no se adopta una medida adecuada, y tampoco obtiene justificación adecuada tras ponerlo en conocimiento del Ministro o de la máxima autoridad afectada, el Defensor del Pueblo:',
 'Incluirá el asunto en su informe anual o especial, con mención de los nombres de las autoridades o funcionarios que hayan adoptado tal actitud.',
 ['Dará traslado al Fiscal General del Estado para exigir responsabilidad penal.', 'Interpondrá recurso de amparo ante el Tribunal Constitucional.', 'Archivará el asunto sin más actuaciones.'],
 'incluirá tal asunto en su informe anual o especial con mención de los nombres de las autoridades o funcionarios que hayan adoptado tal actitud entre los casos en que considerando el Defensor del Pueblo que era posible una solución positiva, ésta no se ha conseguido',
 'la consecuencia es de publicidad parlamentaria (informe con nombres); no hay traslado automático al Fiscal ni recurso de amparo, y el asunto no se archiva.'),
(LO, '31.2', 'm', 'Cuando la intervención se hubiere iniciado a solicitud de un parlamentario o Comisión (art. 10.2), el Defensor del Pueblo:',
 'Les informará de los resultados alcanzados al término de sus investigaciones y, si decide no intervenir, informará razonando su desestimación.',
 ['Solo informará si el parlamentario o la Comisión lo piden de nuevo.', 'Informará únicamente a la Comisión Mixta Congreso-Senado.', 'No está obligado a informar cuando desestime la solicitud.'],
 'el Defensor del Pueblo informará al parlamentario o Comisión competente que lo hubiese solicitado y al término de sus investigaciones, de los resultados alcanzados. Igualmente, cuando decida no intervenir informará razonando su desestimación',
 'hay deber de informar tanto del resultado como de la desestimación (motivada), y al solicitante concreto, no solo a la Comisión Mixta.'),
(RG, '1.2', 'm', 'El Protocolo facultativo de la Convención contra la tortura cuyas funciones de Mecanismo Nacional de Prevención ejerce el Defensor del Pueblo fue hecho en Nueva York el:',
 '18 de diciembre de 2002.',
 ['10 de diciembre de 1948.', '4 de noviembre de 1950.', '18 de diciembre de 1979.'],
 'previstas en el Protocolo facultativo de la Convención contra la tortura y otros tratos o penas crueles, inhumanos o degradantes, hecho en Nueva York el 18 de diciembre de 2002, y dará cuenta de su actividad a las Cortes Generales y al Subcomité para la Prevención de la Tortura de la Organización de las Naciones Unidas',
 'las otras fechas corresponden a otros textos (Declaración Universal de 1948, Convenio de Roma de 1950, CEDAW de 1979); el Protocolo es de 2002.'),
(RG, '3.2', 'm', 'Los Adjuntos del Defensor del Pueblo son directamente responsables de su gestión ante:',
 'El Defensor del Pueblo y la Comisión Mixta Congreso-Senado de relaciones con el Defensor del Pueblo.',
 ['Únicamente las Cortes Generales.', 'Los Presidentes del Congreso y del Senado.', 'La Junta de Coordinación y Régimen Interior.'],
 'Los Adjuntos son directamente responsables de su gestión ante el Defensor del Pueblo y ante la Comisión mixta Congreso-Senado de relaciones con el Defensor del Pueblo',
 'solo el Defensor responde «únicamente» ante las Cortes Generales (art. 3.1); los Adjuntos responden ante él y ante la Comisión Mixta.'),
(RG, '6', 'm', 'El nombramiento del Defensor del Pueblo o de los Adjuntos, si fueran funcionarios públicos, implicará su pase a la situación de:',
 'Excedencia especial o equivalente en la Carrera o Cuerpo de procedencia.',
 ['Servicio activo en su Cuerpo de origen.', 'Servicios especiales con reserva de destino.', 'Excedencia voluntaria por interés particular.'],
 'implicará su pase a la situación de excedencia especial o equivalente en la Carrera o Cuerpo de procedencia',
 'el Reglamento prevé expresamente la excedencia especial o equivalente; permanecer en activo sería incompatible con el cargo (art. 7.1 LO).'),
(RG, '8.e', 'm', 'Corresponde al Defensor del Pueblo mantener relación directa con el Tribunal Constitucional y con el Consejo General del Poder Judicial, igualmente:',
 'A través de sus Presidentes.',
 ['A través del Presidente del Congreso de los Diputados.', 'A través del Fiscal General del Estado.', 'A través de la Comisión Mixta Congreso-Senado.'],
 'Mantener relación directa con el Tribunal Constitucional y con el Consejo General del Poder Judicial, igualmente a través de sus Presidentes',
 'el apartado e) remite a «igualmente», es decir, a través de los Presidentes de ambos órganos; el Fiscal General tiene su propia relación directa (letra f).'),
(RG, '11.1', 'm', 'El informe anual que el Defensor del Pueblo debe dar a las Cortes Generales será sometido, previamente, a:',
 'La Comisión Mixta de relaciones con el Defensor del Pueblo.',
 ['El Pleno del Congreso de los Diputados.', 'Las Mesas del Congreso y del Senado.', 'El Consejo General del Poder Judicial.'],
 'será sometido, previamente, a la Comisión Mixta de relaciones con el Defensor del Pueblo',
 'el filtro previo es la Comisión Mixta, no los Plenos ni las Mesas; el CGPJ no interviene en el informe anual.'),
(RG, '12.4', 'm', 'La admisión definitiva o el rechazo y, en su caso, la resolución última de las quejas formuladas corresponde acordarla:',
 'Al Defensor del Pueblo o al Adjunto en quien delegue o que le sustituya.',
 ['A los Adjuntos, en todo caso.', 'Al Secretario General.', 'A la Junta de Coordinación y Régimen Interior.'],
 'La admisión definitiva o el rechazo y, en su caso, la resolución última de las quejas formuladas corresponde acordarla al Defensor del Pueblo o al Adjunto en quien delegue o que le sustituya',
 'los Adjuntos solo proponen la admisión o el rechazo (art. 12.1.b); la decisión última es del Defensor o del Adjunto delegado o sustituto.'),
(RG, '17', 'm', 'En la Junta de Coordinación y Régimen Interior, el Secretario general actúa como Secretario y asiste a sus reuniones:',
 'Con voz y sin voto.',
 ['Con voz y voto.', 'Sin voz ni voto.', 'Con voto de calidad solo en caso de empate.'],
 'estará compuesta por el Defensor del Pueblo, los Adjuntos y el Secretario general, que actuará como Secretario y asistirá a sus reuniones con voz y sin voto',
 'el Secretario general forma parte de la Junta pero sin derecho de voto, y tampoco tiene voto dirimente.'),
(RG, '40.3', 'm', 'La autorización de transferencias de créditos entre conceptos presupuestarios se realizará por:',
 'El Defensor del Pueblo, con el informe del Interventor de las Cortes Generales.',
 ['La Junta de Coordinación y Régimen Interior, con informe del Secretario General.', 'El Secretario General, con informe del Defensor del Pueblo.', 'Las Mesas del Congreso y del Senado, con informe del Defensor del Pueblo.'],
 'La autorización de transferencias se realizará por el Defensor del Pueblo, con el informe del Interventor de las Cortes Generales',
 'la competencia es del Defensor, con informe del Interventor de las Cortes Generales; ni la Junta ni las Mesas ni el Secretario General la ejercen.'),
# ---------- DIFÍCILES (15)
(RG, '16.1.d', 'd', 'El cese de los Adjuntos del Defensor del Pueblo por notoria negligencia en el cumplimiento de las obligaciones y deberes del cargo exigirá:',
 'Una propuesta razonada del Defensor del Pueblo, aprobada por la Comisión mixta Congreso-Senado con el mismo procedimiento y mayoría que para otorgar la conformidad previa a su nombramiento, y con audiencia del interesado.',
 ['Una propuesta del Presidente del Congreso, aprobada por las tres quintas partes de cada Cámara.', 'Una decisión libre del Defensor del Pueblo, con audiencia del interesado.', 'Una propuesta razonada del Defensor del Pueblo, aprobada por mayoría absoluta del Senado.'],
 'En este caso, el cese exigirá una propuesta razonada del Defensor del Pueblo, que habrá de ser aprobada por la Comisión mixta Congreso-Senado, de acuerdo con el mismo procedimiento y mayoría requerida para otorgar la conformidad previa para su nombramiento, y con audiencia del interesado',
 'la negligencia notoria es la única causa de cese que exige propuesta razonada y aprobación de la Comisión Mixta con audiencia del interesado; las otras opciones cambian el órgano o la mayoría.'),
(RG, '38.4', 'd', 'Las anotaciones en la hoja de servicio relativas a sanciones podrán cancelarse a petición del funcionario una vez transcurrido un período equivalente al de prescripción de la falta. Si el funcionario vuelve a incurrir en falta (reincidencia), los plazos de cancelación serán:',
 'De duración doble.',
 ['De duración triple.', 'Los mismos que para la primera falta.', 'De un año en todo caso.'],
 'La cancelación no impedirá la apreciación de reincidencia si el funcionario vuelve a incurrir en falta; en este caso, los plazos de cancelación serán de duración doble',
 'la reincidencia duplica el plazo de cancelación; no se triplica, no se mantiene ni se fija en un año.'),
(RG, 'disp. transitoria', 'd', 'Transcurridos dos años desde la toma de posesión del primer Consejo Asesor del Mecanismo Nacional de Prevención, los Vocales que deban ser renovados se determinarán mediante sorteo. Si el número de Vocales fuere de nueve, se renovarán:',
 'Cuatro puestos.',
 ['Cinco puestos.', 'Tres puestos.', 'Dos puestos.'],
 'Transcurridos dos años desde la toma de posesión del primer Consejo Asesor del Mecanismo Nacional de Prevención se determinarán mediante sorteo los Vocales que deban ser renovados. Si el número de Vocales del Consejo fuere de nueve ser renovarán cuatro puestos',
 'la renovación es por mitades (art. 20.1); con nueve Vocales se renuevan cuatro.'),
(RG, '19.5.d', 'd', 'Los hasta dos Vocales del Consejo Asesor designados a propuesta conjunta de los organismos con los que el Defensor del Pueblo tenga suscritos convenios de colaboración: las propuestas no podrán incluir más que:',
 'Un representante por entidad.',
 ['Dos representantes por entidad.', 'Tres representantes en total.', 'Un representante por Comunidad Autónoma.'],
 'Las propuestas que se formulen no podrán incluir más que un representante por entidad',
 'el límite es un representante por entidad; no hay tope global de tres ni criterio territorial.'),
(RG, '35.2', 'd', 'Los asesores del Defensor del Pueblo, previo reconocimiento de compatibilidad, podrán ser contratados para funciones docentes o de investigación en Universidades u otras instituciones académicas análogas. Tales actividades se desempeñarán:',
 'En régimen de dedicación a tiempo parcial y sin menoscabar la prestación del servicio en el Defensor del Pueblo.',
 ['En régimen de dedicación exclusiva con la Institución.', 'A tiempo completo, con reducción de jornada en el Defensor del Pueblo.', 'Con libertad de horario durante la jornada laboral en el Defensor del Pueblo.'],
 'tales actividades se desempeñarán en régimen de dedicación a tiempo parcial y sin que puedan menoscabar la prestación del servicio en el Defensor del Pueblo',
 'la excepción a la dedicación exclusiva (art. 35.1) es solo docente o investigadora, a tiempo parcial y sin perjudicar el servicio.'),
(RG, '28.3', 'd', '¿Qué competencia no podrá delegar el Defensor del Pueblo en los órganos similares de las Comunidades Autónomas?',
 'La atribuida por el artículo 54 de la Constitución, en orden a la defensa de los derechos comprendidos en su título primero.',
 ['La atribuida por el artículo 103 de la Constitución, en orden a la actuación de la Administración.', 'La atribuida por el artículo 162 de la Constitución, en orden a la legitimación para recurrir.', 'La atribuida por el artículo 55 de la Constitución, en orden a la suspensión de derechos.'],
 'El Defensor del Pueblo no podrá delegar en los órganos similares de las Comunidades Autónomas la competencia que le ha sido atribuida por el artículo 54 de la Constitución, en orden a la defensa de los derechos comprendidos en su título primero',
 'el artículo clave es el 54 CE (institución del Defensor del Pueblo); los otros artículos constitucionales se refieren a la Administración, al Tribunal Constitucional y a los estados excepcionales.'),
(RG, '26.1', 'd', 'El Secretario general, como responsable del Registro, informará del número y naturaleza de los escritos dirigidos a la Oficina del Defensor del Pueblo:',
 'Al Adjunto Primero y, en su defecto, al Segundo.',
 ['Directamente al Defensor del Pueblo y, en su defecto, al Adjunto Primero.', 'Al Adjunto Segundo y, en su defecto, al Primero.', 'A la Junta de Coordinación y Régimen Interior en cada sesión.'],
 'El Secretario general, en cuanto responsable del Registro, informará al Adjunto Primero y, en su defecto, al Segundo, del número y naturaleza de los escritos dirigidos a la Oficina del Defensor del Pueblo, a los efectos que proceda',
 'el orden es Adjunto Primero y, en su defecto, Segundo (no al revés), y no se informa directamente al Defensor ni a la Junta.'),
(LO, '33.2', 'd', 'En el informe anual no constarán datos personales que permitan la pública identificación de los interesados en el procedimiento investigador, sin perjuicio de lo dispuesto en:',
 'El artículo 24.1, sobre la persistencia en una actitud hostil o entorpecedora de la labor de investigación.',
 ['El artículo 22.2, sobre la reserva de las investigaciones.', 'El artículo 17.3, sobre las quejas anónimas.', 'El artículo 33.1, sobre el número y tipo de quejas.'],
 'En el informe no constarán datos personales que permitan la pública identificación de los interesados en el procedimiento investigador, sin perjuicio de lo dispuesto en el artículo veinticuatro punto uno',
 'la salvedad es el art. 24.1 (informe especial y mención en el informe anual de quien persiste en entorpecer); los demás artículos regulan otras cuestiones.'),
(RG, '12.5', 'd', 'El Defensor del Pueblo podrá recabar el conocimiento, dirección o tratamiento de cualquier queja o investigación cuyo trámite corresponda a los Adjuntos, oída:',
 'La Junta de Coordinación y Régimen Interior.',
 ['La Comisión Mixta Congreso-Senado.', 'El Consejo Asesor del Mecanismo Nacional de Prevención.', 'El Secretario General.'],
 'El Defensor del Pueblo podrá recabar, oída la Junta de Coordinación y Régimen Interior, el conocimiento, dirección o tratamiento de cualquier queja o investigación cuyo trámite corresponda a los Adjuntos',
 'el órgano consultivo interno previsto es la Junta; ni la Comisión Mixta, ni el Consejo Asesor (propio del MNP), ni el Secretario General.'),
(RG, '20.4', 'd', 'Cumplido el período de cuatro años de su designación, los Vocales cesantes del Consejo Asesor:',
 'Continuarán ejerciendo sus funciones hasta la designación de los nuevos Vocales.',
 ['Cesarán automáticamente y el Consejo funcionará sin ellos hasta la nueva designación.', 'Serán sustituidos interinamente por los Adjuntos.', 'Continuarán ejerciendo sus funciones durante un máximo de seis meses.'],
 'los Vocales cesantes continuarán ejerciendo sus funciones hasta la designación de los nuevos Vocales',
 'no hay cese automático, ni sustitución por los Adjuntos, ni límite de seis meses: se prorroga hasta que se designe a los nuevos Vocales.'),
(LO, '31.3', 'd', 'El Defensor del Pueblo comunicará el resultado positivo o negativo de sus investigaciones:',
 'A la autoridad, funcionario o dependencia administrativa acerca de la cual se haya suscitado la queja.',
 ['A la Comisión Mixta Congreso-Senado, que lo remitirá a la autoridad afectada.', 'Únicamente a las Cortes Generales en el informe anual.', 'Al Ministro del Departamento afectado, en todo caso.'],
 'El Defensor del Pueblo comunicará el resultado positivo o negativo de sus investigaciones a la autoridad, funcionario o dependencia administrativa acerca de la cual se haya suscitado',
 'la comunicación es directa a la autoridad, funcionario o dependencia investigada, sin pasar por la Comisión Mixta y sin limitarse al informe anual ni al Ministro.'),
(RG, '29.2', 'd', 'En las actuaciones de oficio relativas a la Administración de Justicia, el Defensor del Pueblo actuará coordinadamente con:',
 'El Presidente del Consejo General del Poder Judicial y el Fiscal General del Estado, en su caso, a quienes informará del resultado de sus gestiones.',
 ['El Presidente del Tribunal Supremo y el Ministro de Justicia.', 'El Presidente del Tribunal Constitucional y el Fiscal General del Estado.', 'La Sala de lo Penal del Tribunal Supremo y la Comisión Mixta.'],
 'En las actuaciones de oficio, el Defensor del Pueblo actuará coordinadamente con el Presidente del Consejo General del Poder Judicial y el Fiscal general del Estado, en su caso, a quienes informará del resultado de sus gestiones',
 'los interlocutores son el Presidente del CGPJ y el Fiscal General del Estado; el Ministro de Justicia, el Tribunal Supremo o el Constitucional no figuran en el art. 29.2.'),
(RG, '30.5', 'd', 'La referencia a documentos reservados en los informes al Congreso y al Senado:',
 'Será prudentemente apreciada por el Defensor del Pueblo.',
 ['Estará prohibida en todo caso.', 'Requerirá la autorización previa de la Comisión Mixta Congreso-Senado.', 'Requerirá el acuerdo de las Mesas de ambas Cámaras.'],
 'La referencia a documentos reservados en los informes al Congreso y al Senado será prudentemente apreciada por el Defensor del Pueblo',
 'la prohibición absoluta es para los documentos secretos (art. 30.4); para los reservados decide el Defensor con prudencia, sin autorización previa de otros órganos.'),
(LO, '20.3', 'd', 'Si un funcionario afectado se niega a la entrevista ampliatoria de datos que le proponga el Defensor del Pueblo, este podrá requerirle para que:',
 'Manifieste por escrito las razones que justifiquen tal decisión.',
 ['Comparezca ante la Comisión Mixta Congreso-Senado.', 'Acepte la entrevista bajo apercibimiento de sanción directa por el Defensor del Pueblo.', 'Preste declaración ante el Fiscal General del Estado.'],
 'Los funcionarios que se negaren a ello podrán ser requeridos por aquél para que manifiesten por escrito las razones que justifiquen tal decisión',
 'la consecuencia es solo el requerimiento de explicación escrita; el Defensor no sanciona y no intervienen ni la Comisión Mixta ni el Fiscal General.'),
(LO, 'disp. transitoria', 'd', '¿Cuándo podrá el Defensor del Pueblo proponer a las Cortes Generales, en informe razonado, las modificaciones que entienda que deben realizarse a la Ley Orgánica?',
 'A los cinco años de entrada en vigor de la Ley.',
 ['A los tres años de entrada en vigor de la Ley.', 'A los diez años de entrada en vigor de la Ley.', 'Al término de cada legislatura.'],
 'A los cinco años de entrada en vigor de la presente Ley, el Defensor del Pueblo podrá proponer a las Cortes Generales y en informe razonado aquellas modificaciones que entienda que deben realizarse a la misma',
 'la disposición transitoria fija expresamente cinco años; no es un plazo móvil por legislatura ni de tres o diez años.'),
]

# Alarga distractores (falsos según el texto) para que la correcta no sea siempre la opción más larga. {nº de pregunta: {índice de distractor: texto}}
OV = {
 4: {0: 'Previa reclamación por escrito dirigida al superior jerárquico y transcurrido el plazo de un mes sin respuesta.'},
 7: {0: 'En tres servicios: el Económico, el de Régimen Interior y el de Registro, Archivo y Biblioteca, auxiliados cada uno por un Asesor.'},
 9: {2: 'A los Adjuntos y también a los asesores y demás personal de la Institución mientras presten servicio en ella.'},
 12: {0: 'El Presidente del Congreso de los Diputados, hasta que las Cortes procedan a la nueva designación.'},
 17: {1: 'La nacionalidad, la residencia y el sexo no pueden constituir impedimento, como tampoco cualquier relación especial de sujeción o dependencia de una Administración o Poder público.'},
 18: {0: 'Suspenderá la actividad del Defensor del Pueblo mientras dure la situación, salvo para las quejas ya admitidas a trámite antes de la declaración, que se resolverán con posterioridad.'},
 19: {0: 'Ejercerán la supervisión en exclusiva y sin intervención alguna del Defensor del Pueblo, que no podrá solicitar su cooperación ni actuar en su ámbito.'},
 20: {2: 'Las rechazará siempre y no podrá investigar tampoco los problemas generales que planteen, aunque afecten a un gran número de ciudadanos y a la propia Administración.'},
 21: {},
 23: {1: 'Por escrito, pero dirigido únicamente al funcionario, con copia a su inmediato superior para su conocimiento.'},
 24: {0: 'Lo que acuerde el Ministro del Departamento afectado, que podrá levantar la reserva de las actuaciones cuando lo considere oportuno.'},
 25: {0: 'Sancionar directamente a los particulares, con multa o suspensión de la actividad, previa audiencia del interesado.'},
 26: {0: 'Dará traslado de los antecedentes al Fiscal General del Estado para exigir responsabilidad penal a las autoridades y funcionarios que hayan adoptado esa actitud.'},
 27: {0: 'Solo informará si el parlamentario o la Comisión lo piden de nuevo por escrito una vez finalizadas sus investigaciones, y no si decide no intervenir.'},
 29: {0: 'Únicamente ante las Cortes Generales, a través de los Presidentes del Congreso y del Senado, sin responsabilidad alguna ante el Defensor.'},
 30: {0: 'Servicio activo en su Cuerpo de origen, con reserva de la plaza que ocupasen, durante todo el mandato.'},
 32: {0: 'El Pleno del Congreso de los Diputados, reunido en sesión extraordinaria.'},
 33: {0: 'A los Adjuntos, en todo caso, sin que el Defensor del Pueblo pueda avocar ni sustituirles en ello.'},
 36: {1: 'Una decisión libre del Defensor del Pueblo, con audiencia del interesado y comunicación posterior a la Comisión mixta Congreso-Senado y a los Presidentes de ambas Cámaras, sin necesidad de más trámites ni mayorías especiales.'},
 40: {1: 'A tiempo completo, con una reducción proporcional de su jornada en el Defensor del Pueblo y siempre que lo autorice el Secretario general.'},
 41: {0: 'La atribuida por el artículo 103 de la Constitución, en orden a la actuación y organización de la Administración pública.'},
 43: {0: 'El artículo 22.2, sobre la absoluta reserva con que se verifican las investigaciones y los trámites procedimentales.'},
 46: {0: 'A la Comisión Mixta Congreso-Senado, que lo remitirá a la autoridad, funcionario o dependencia afectada para su conocimiento.'},
 47: {0: 'El Presidente del Tribunal Supremo y el Ministro de Justicia, a quienes informará del resultado de sus gestiones y de las medidas adoptadas en las actuaciones de oficio.'},
}
for k in (24, 25, 26, 43, 12): OV.pop(k, None)   # se dejan sin alargar para no sesgar al revés
Q = [list(q) for q in Q]
for n, d in OV.items():
    for i, t in d.items(): Q[n-1][5][i] = t
Q[20][4] = 'Veintidós.'   # 14-ia-21: respuesta corta, igual que las demás opciones
assert len(Q) == 50, len(Q)
cnt = {k: sum(1 for q in Q if q[2] == k) for k in 'fmd'}
assert cnt == {'f': 10, 'm': 25, 'd': 15}, cnt

# posiciones de la letra correcta equilibradas (A=12, B=13, C=12, D=13) y repartidas
pos = [0]*12 + [1]*13 + [2]*12 + [3]*13
random.Random(14).shuffle(pos)

out = []
for i, (norma, art, dif, enun, ok, dis, cita, why) in enumerate(Q):
    p = pos[i]
    ops = list(dis); ops.insert(p, ok)
    L = 'ABCD'[p]
    refn, art_det = REF[norma]
    exp = ('<span class="ex-resp">Respuesta correcta: <b>%s</b> · <mark class="ex-key">%s</mark></span>' % (L, ok.rstrip('.')) +
           'El <span class="ref-norma">%s</span> dispone: <span class="ref-concepto">"%s"</span>. ' % (refn.format(a=art), cita) +
           'Por qué fallan las otras: %s ' % why +
           '<em style="color:var(--texto-gris)">(Pregunta generada por IA · Dificultad: %s)</em>' % DIF[dif][1])
    out.append({'id': '14-ia-%d' % (i+1), 'pregunta': PRE[norma] + art + '. ' + enun, 'opciones': ops, 'correcta': p,
                'dificultad': DIF[dif][0], 'explicacion': exp, 'apartado': AP[norma]})

json.dump(out, open(sys.argv[1], 'w', encoding='utf-8'), ensure_ascii=False)
# estadísticas
print('letras', {k: sum(1 for o in out if o['correcta'] == v) for k, v in zip('ABCD', range(4))})
mas_larga = sum(1 for o in out if len(o['opciones'][o['correcta']]) == max(len(x) for x in o['opciones']))
print('correcta = más larga en', mas_larga, 'de 50')
